### PR TITLE
Fix linter

### PR DESCRIPTION
**Pull request by arreche**
The linter was broken because I've forgot to add `eslint` to dev dependencies.

### CODE REVIEW

**Comment by yeraycaballero** [comment]
Hi @arreche, I tired to lint the code with npm run lint but it think is not processing any file. I'll tray to play with it when I have a chance to see what's going on

**Comment by arreche** [comment]
Could you please give more details about the problem? Did you remember to update dependencies running `npm install` before to try it?

Well. If I introduce a typo (Deleting the closing slash `/`  from the `App` node in `src/index.js`)
```javascript
ReactDOM.render(<App >, document.getElementById('root'));
```

Then I get the following error

```
$ npm run lint

> @ lint /Users/one/dev/partners
> eslint src


/Users/one/dev/partners/src/index.js
  5:23  error  Parsing error: Unterminated JSX contents

✖ 1 problem (1 error, 0 warnings)
```

**Comment by yeraycaballero** [comment]
Forget about that. My fault, I changed the indentation and I didn't see anything

**Comment by arreche** [comment]
Oh I see. Perhaps you want to add more rules to the `.eslintrc` file.

See https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-indent.md

By the way, I found some kind of standard rules in [eslint-config-standard-react](https://github.com/feross/eslint-config-standard-react)

**Pull request merged**
