### PR TITLE
Search feature

### PR DESCRIPTION
**Pull request by raisen**
Search feature implementation using our static mocked data structure.

### CODE REVIEW

**Comment by raisen** [comment]
I'm checking why the test failed and will push a fix soon.

**Comment by arreche** [comment]
It looks good to me. What do you think @yeraycaballero?

**Comment by yeraycaballero** [comment]
It's good to me too.Go ahead.

**Comment by arreche** [comment]
Usually who open a pull request is responsable to merge it but I'm going to merge it myself to speed up the things.

**Pull request merged**
